// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/aws/aws-sdk-go-v2/service/sqs/types"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// DeleteMessage provides a mock function with given fields: ctx, queueURL, receiptHandle
func (_m *Service) DeleteMessage(ctx context.Context, queueURL string, receiptHandle string) error {
	ret := _m.Called(ctx, queueURL, receiptHandle)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, queueURL, receiptHandle)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessMessage provides a mock function with given fields: ctx, message
func (_m *Service) ProcessMessage(ctx context.Context, message string) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for ProcessMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReceiveMessages provides a mock function with given fields: ctx, queueURL, batchSize, retries
func (_m *Service) ReceiveMessages(ctx context.Context, queueURL string, batchSize int, retries int) ([]types.Message, error) {
	ret := _m.Called(ctx, queueURL, batchSize, retries)

	if len(ret) == 0 {
		panic("no return value specified for ReceiveMessages")
	}

	var r0 []types.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]types.Message, error)); ok {
		return rf(ctx, queueURL, batchSize, retries)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []types.Message); ok {
		r0 = rf(ctx, queueURL, batchSize, retries)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, queueURL, batchSize, retries)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
