# Default properties file for global environment
router:
  port: '8084'
  name: 'tweets-service'

log:
  level: debug
  path: '/event-processor.log'

aws:
  region: 'us-east-1'

redis:
  host: 'localhost'
  port: 6379
  db: 0
  timeout: 5

sqs:
  endpoint: 'http://localhost:4566'

processors:
  tweets:
    endpoint: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/tweets"