# Properties file for docker test
router:
  port: '8080'
  name: 'tweets-service'

log:
  level: debug
  path: '/tweets-service.log'

aws:
  region: 'us-east-1'

dynamo:
  endpoint: 'http://localstack:4566'

processors:
  tweets:
    endpoint: 'http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/tweets'

redis:
  host: 'redis'
  port: 6379
  db: 0
  timeout: 5